name: "Run CronitorCLI tests"

on:
  - push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3

      - name: Build binary
        run: go build -o cronitor main.go

      - name: Activity
        working-directory: tests
        run: bash test-activity.sh

      - name: Configure
        working-directory: tests
        run: bash test-configure.sh

      - name: Discover
        working-directory: tests
        run: bash test-discover.sh

      - name: Exec
        working-directory: tests
        run: bash test-exec.sh

      - name: List
        working-directory: tests
        run: bash test-list.sh

      - name: Ping
        working-directory: tests
        run: bash test-ping.sh

      - name: Status
        working-directory: tests
        run: bash test-status.sh
