name: "Run CronitorCLI tests"

on:
  - push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Build binary
        run: go build -o cronitor main.go

      - name: Run tests
        working-directory: tests
        run: |
          sudo su -
          bats *.bats
