name: "Run CronitorCLI tests"

on:
  - push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3

      - name: Build binary
        run: go build -o cronitor main.go

      - name: Run tests
        run: bash test-all.sh
        working-directory: tests
